name: WebWash Tailwind Site Demo
type: Site
install:
  - announcements_feed
  - automated_cron
  - big_pipe
  - block
  - block_content
  - breakpoint
  - ckeditor5
  - comment
  - config
  - contact
  - contextual
  - datetime
  - dblog
  - dynamic_page_cache
  - editor
  - field
  - field_ui
  - file
  - filter
  - help
  - history
  - image
  - layout_builder
  - layout_discovery
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - mysql
  - node
  - options
  - page_cache
  - path
  - path_alias
  - search
  - system
  - taxonomy
  - text
  - toolbar
  - update
  - user
  - views
  - views_ui
  - canvas
  - drupal_cms_helper
  - gin_toolbar
  - olivero
  - claro
  - canvas_stark
  - webwash_tailwind
  - gin
config:
  actions:
    system.diff:
      simpleConfigUpdate:
        context:
          lines_leading: 2
          lines_trailing: 2
    system.feature_flags:
      simpleConfigUpdate:
        linkset_endpoint: false
    system.image.gd:
      simpleConfigUpdate:
        jpeg_quality: 75
    system.logging:
      simpleConfigUpdate:
        error_level: hide
    system.mail:
      simpleConfigUpdate:
        interface:
          default: php_mail
        mailer_dsn:
          scheme: sendmail
          host: default
          user: null
          password: null
          port: null
          options: {  }
    system.maintenance:
      simpleConfigUpdate:
        langcode: en
        message: '@site is currently under maintenance. We should be back shortly. Thank you for your patience.'
    user.mail:
      simpleConfigUpdate:
        langcode: en
        cancel_confirm:
          subject: 'Account cancellation request for [user:display-name] at [site:name]'
          body: |-
            [user:display-name]

            A request to cancel your account has been made at [site:name].

            You may now cancel your account on [site:url-brief] by clicking this link or copying and pasting it into your browser:

            [user:cancel-url]

            NOTE: The cancellation of your account is not reversible.

            This link expires in one day and nothing will happen if it is not used.

            --  [site:name] team
        password_reset:
          subject: 'Replacement login information for [user:display-name] at [site:name]'
          body: |-
            [user:display-name],

            A request to reset the password for your account has been made at [site:name].

            You may now log in by clicking this link or copying and pasting it into your browser:

            [user:one-time-login-url]

            This link can only be used once to log in and will lead you to a page where you can set your password. It expires after one day and nothing will happen if it's not used.

            --  [site:name] team
        register_admin_created:
          subject: 'An administrator created an account for you at [site:name]'
          body: |-
            [user:display-name],

            A site administrator at [site:name] has created an account for you. You may now log in by clicking this link or copying and pasting it into your browser:

            [user:one-time-login-url]

            This link can only be used once to log in and will lead you to a page where you can set your password.

            After setting your password, you will be able to log in at [site:login-url] in the future using:

            username: [user:name]
            password: Your password

            --  [site:name] team
        register_no_approval_required:
          subject: 'Account details for [user:display-name] at [site:name]'
          body: |-
            [user:display-name],

            Thank you for registering at [site:name]. You may now log in by clicking this link or copying and pasting it into your browser:

            [user:one-time-login-url]

            This link can only be used once to log in and will lead you to a page where you can set your password.

            After setting your password, you will be able to log in at [site:login-url] in the future using:

            username: [user:name]
            password: Your password

            --  [site:name] team
        register_pending_approval:
          subject: 'Account details for [user:display-name] at [site:name] (pending admin approval)'
          body: |-
            [user:display-name],

            Thank you for registering at [site:name]. Your application for an account is currently pending approval. Once it has been approved, you will receive another email containing information about how to log in, set your password, and other details.

            --  [site:name] team
        register_pending_approval_admin:
          subject: 'Account details for [user:display-name] at [site:name] (pending admin approval)'
          body: |-
            [user:display-name] has applied for an account.

            [user:edit-url]
        status_activated:
          subject: 'Account details for [user:display-name] at [site:name] (approved)'
          body: |-
            [user:display-name],

            Your account at [site:name] has been activated.

            You may now log in by clicking this link or copying and pasting it into your browser:

            [user:one-time-login-url]

            This link can only be used once to log in and will lead you to a page where you can set your password.

            After setting your password, you will be able to log in at [site:login-url] in the future using:

            username: [user:account-name]
            password: Your password

            --  [site:name] team
        status_blocked:
          subject: 'Account details for [user:display-name] at [site:name] (blocked)'
          body: |-
            [user:display-name],

            Your account on [site:name] has been blocked.

            --  [site:name] team
        status_canceled:
          subject: 'Account details for [user:display-name] at [site:name] (canceled)'
          body: |-
            [user:display-name],

            Your account on [site:name] has been canceled.

            --  [site:name] team
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions:
          contact__site_page:
            menu_name: footer
            parent: ''
            weight: 0
            expanded: false
            enabled: true
          standard__front_page:
            menu_name: main
            parent: ''
            weight: -50
            expanded: false
            enabled: true
    system.advisories:
      simpleConfigUpdate:
        enabled: true
        interval_hours: 6
    system.cron:
      simpleConfigUpdate:
        threshold:
          requirements_warning: 172800
          requirements_error: 1209600
        logging: true
    system.date:
      simpleConfigUpdate:
        first_day: 0
        country:
          default: null
        timezone:
          default: Europe/Zagreb
          user:
            configurable: true
            default: 0
            warn: false
    system.file:
      simpleConfigUpdate:
        allow_insecure_uploads: false
        default_scheme: public
        temporary_maximum_age: 21600
    system.image:
      simpleConfigUpdate:
        toolkit: gd
    system.performance:
      simpleConfigUpdate:
        cache:
          page:
            max_age: 0
        css:
          preprocess: false
          gzip: true
        fast_404:
          enabled: true
          paths: '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i'
          exclude_paths: '/\/(?:styles|imagecache)\//'
          html: '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>'
        js:
          preprocess: false
          gzip: true
    system.site:
      simpleConfigUpdate:
        langcode: en
        name: 'Drush Site-Install'
        mail: admin@example.com
        slogan: ''
        page:
          403: ''
          404: ''
          front: /page/1
        admin_compact_mode: false
        weight_select_max: 100
        default_langcode: en
        mail_notification: null
    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: webwash_tailwind
    system.theme.global:
      simpleConfigUpdate:
        favicon:
          mimetype: image/vnd.microsoft.icon
          path: ''
          url: ''
          use_default: true
        features:
          comment_user_picture: true
          comment_user_verification: true
          favicon: true
          node_user_picture: true
        logo:
          path: ''
          url: null
          use_default: true
    user.flood:
      simpleConfigUpdate:
        uid_only: false
        ip_limit: 50
        ip_window: 3600
        user_limit: 5
        user_window: 21600
    user.settings:
      simpleConfigUpdate:
        langcode: en
        anonymous: Anonymous
        verify_mail: true
        notify:
          cancel_confirm: true
          password_reset: true
          status_activated: true
          status_blocked: false
          status_canceled: false
          register_admin_created: true
          register_no_approval_required: true
          register_pending_approval: true
        register: admin_only
        cancel_method: user_cancel_block
        password_reset_timeout: 86400
        password_strength: true
    user.role.anonymous:
      grantPermissions:
        - 'access comments'
        - 'access content'
        - 'access site-wide contact form'
        - 'search content'
        - 'use text format restricted_html'
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'access comments'
        - 'access content'
        - 'access site-wide contact form'
        - 'delete own files'
        - 'post comments'
        - 'search content'
        - 'skip comment approval'
        - 'use text format basic_html'
        - 'view media'
